import Head from "next/head";
import { Layout } from "../core/layout/Layout";
import { MeetupsContainer } from "../core/components/MeetupsContainer";
import { MeetupCard } from "../core/components/MeetupCard";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Techmeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <MeetupsContainer>
          <MeetupCard />
          <MeetupCard />
          <MeetupCard />
          <MeetupCard />
          <MeetupCard />
        </MeetupsContainer>
      </Layout>
    </div>
  );
}
