import Head from "next/head";
import { Layout } from "../core/layout/Layout";
import { MeetupsContainer } from "../core/components/MeetupsContainer";
import { MeetupCard } from "../core/components/MeetupCard";
import { Text, Center } from "@chakra-ui/layout";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Techmeet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Center my={10}>
          <Text color="#fff" fontSize="30">
            Below you will find all the Tech Meetings in Romania
          </Text>
        </Center>
        <MeetupsContainer>
          <MeetupCard />
          <MeetupCard />
          <MeetupCard />
          <MeetupCard />
        </MeetupsContainer>
      </Layout>
    </div>
  );
}
